version : "3"
services :
   db:
     image: postgres:11
     container_name: pgdb
     volumes:
       - db:/var/lib/postgresql/data
     environment:
       - POSTGRES_DB=postgres
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
   django_app1 :
     build : .
     container_name: django
     command : python3 manage.py runserver 0.0.0.0:8000
     ports:
         - "8000:8000"

volumes:
  db:
    driver: local

